version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: "rabbitmq"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile.celery
    container_name: "celery_worker"
    command: celery -A app.celery_app worker --loglevel=DEBUG
    depends_on:
      - rabbitmq
    environment:
      - CELERY_BROKER_URL=pyamqp://guest@rabbitmq//

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    container_name: fastapi_app
    ports:
      - "8000:8000"
    environment:
      - UVICORN_CMD=uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app

networks:
  default:
    driver: bridge
