// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-F6iYS87WEqWSGl0ylkzin47yhFmm9G8',
    appId: '1:344403982969:web:a13b07bb41cbcddfd8f2a8',
    messagingSenderId: '344403982969',
    projectId: 'meal-997fe',
    authDomain: 'meal-997fe.firebaseapp.com',
    storageBucket: 'meal-997fe.firebasestorage.app',
    measurementId: 'G-6SQCSZHPCJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1-nUcRJEG5P4e0EJU1Wz27tMl6gbJFlE',
    appId: '1:344403982969:android:431bdcd10d4e567dd8f2a8',
    messagingSenderId: '344403982969',
    projectId: 'meal-997fe',
    storageBucket: 'meal-997fe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnrNBOi38kJY0qht5xKA3jZ6oXV9vCEQs',
    appId: '1:344403982969:ios:dc2d3673c9de3e3bd8f2a8',
    messagingSenderId: '344403982969',
    projectId: 'meal-997fe',
    storageBucket: 'meal-997fe.firebasestorage.app',
    androidClientId: '344403982969-dnfa6g3776cfm2kr343ah63trmt0pufl.apps.googleusercontent.com',
    iosClientId: '344403982969-t5n4bq0863o3q0f8amejmh26pugfto5t.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled',
  );
}
