part of 'gallery_screen.dart';

late TabController _tabController;
late List<ImageWithDate> filteredImages;
bool isSearching = false;
bool isSelecting = false;
String currentCategory = 'Recent';
String currentView = 'grid';
DateTime? searchDate;
Set<String> selectedImages = {};
Set<String> favoriteImages = {};
TextEditingController searchController = TextEditingController();
ScrollController scrollController = ScrollController();
String? selectedFilter;
bool _showScrollToTop = false;
bool isScrollingUp = false;
bool _isLoadingMore = false;
bool _hasMoreImages = true;
int _currentPage = 0;
Map<String, List<ImageWithDate>> _loadedImages = {};
Map<String, List<ImageWithDate>> categorizedImages = {};
double _scrollThreshold = 0.8;
bool _isProcessingFaces = false;
List<PhotoMetadata> _allPhotos = [];
String sortBy = 'date';
bool sortAscending = false;
final imageOptimizer = ImageOptimizer();
final GalleryManager _galleryManager = GalleryManager();
final List<String> viewTabs = ['Photos', 'Albums', 'People', 'Places'];
Set<String> _knownPhotos = {};
Map<String, List<String>> _faceClusters = {};
bool _faceClustersCalculated = false;
const int _pageSize = 20;
